### PR TITLE
Include the file name in the results

### PR DESCRIPTION
**Pull request by yyoncho**

### CODE REVIEW

**Comment by andreasjansson** [comment]
:+1: this. In `go-lsp` usability is quite low unless you search for a very specific symbol:
image

**Comment by leungbk** [comment]
It would be great to see this merged at some point. `ivy` is quite flaky for me.

**Comment by yyoncho** [comment]
I will try to do it today.

**Comment by yyoncho** [comment]
I updated the fix, but I performed only limited testing, so it will be great if
someone could test it too. (Otherwise I will push the fix one I test it enough)

**Comment by leungbk** [comment]
Thanks for updating. It's working well for me.

**Pull request merged**
